In [1]:
"hello wrold"

'hello wrold'

In [2]:
'''
1. basic array creation
2. array generation function
3. random generation function
4. array attributes
5. arrays methods
6. reshaping and resizing
'''


'\n1. basic array creation\n2. array generation function\n3. random generation function\n4. array attributes\n5. arrays methods\n6. reshaping and resizing\n'

1. basic array creation

In [3]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
lst = [1,2,3,4, "Hello"]
lst

[1, 2, 3, 4, 'Hello']

In [10]:
arr1 = np.array(lst)
arr1

array(['1', '2', '3', '4', 'Hello'], dtype='<U21')

In [11]:
lst1 = [1,2,3,4.3]
lst1

[1, 2, 3, 4.3]

In [12]:
arr2 = np.array(lst1)
arr2

array([1. , 2. , 3. , 4.3])

In [13]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# vectors - one dimentional
# above 2 dimention - tensors

In [16]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.arange(1,10,3)
arr

array([1, 4, 7])

In [ ]:
arr_zeros = np.zeros(6)
arr_zeros # vector

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr_zeros2 = np.zeros((6,6))
arr_zeros2 # matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.zeros((3,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arr_zeros_int = np.zeros(5, dtype=int)
arr_zeros_int

array([0, 0, 0, 0, 0])

In [26]:
arr_zeros_int = np.zeros((3,3), dtype=int)
arr_zeros_int

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
arr_one = np.ones((2,5), dtype=int)
arr_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
'''
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

Parameters
start : array_like
    The starting value of the sequence.
stop : array_like

'''

arr = np.linspace(1,10, 4) # linear space - space between the values will be same
arr

array([ 1.,  4.,  7., 10.])

In [44]:
# arr = np.linspace(1,5,2)
# arr = np.linspace(1,5,3)
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [45]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

2. array generation function
3. random generation function


In [ ]:
'''
normalization gives values between 0 and 1
standardization gives values between 3 and -3
'''

In [47]:
# normalization values
np.random.rand(10)

array([0.37369638, 0.79726566, 0.08587988, 0.59352069, 0.13008135,
       0.81859858, 0.63662062, 0.04619785, 0.62902621, 0.43781895])

In [52]:
# standardization values
np.random.randn(10)

array([ 0.1239727 , -2.32048898, -1.88755446,  0.41522587, -1.18451623,
       -0.0880705 , -0.51073338, -0.96453467,  1.32657569,  1.69914392])

In [54]:
np.random.randint(10) # gives only one random number between 0 and n

6

In [55]:
np.random.randint(2, size=2)

array([1, 0], dtype=int32)

In [56]:
np.random.randint(1, size=5)

array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
np.random.randint(2, size=2)

In [57]:
np.random.randint(2, size=(3,6))

array([[0, 1, 0, 0, 1, 0],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0]], dtype=int32)

In [58]:
np.random.randint(10,12, size=10)

array([10, 10, 11, 10, 10, 11, 10, 11, 10, 10], dtype=int32)

In [59]:
np.random.randint(10,12, size=(10,10))


array([[11, 10, 11, 10, 10, 10, 11, 11, 11, 11],
       [10, 11, 11, 10, 11, 10, 10, 10, 10, 10],
       [10, 11, 10, 10, 11, 10, 10, 10, 10, 10],
       [11, 10, 10, 10, 10, 11, 11, 11, 10, 11],
       [11, 11, 10, 11, 11, 11, 11, 10, 11, 10],
       [11, 10, 11, 11, 11, 11, 10, 10, 11, 11],
       [11, 11, 11, 10, 10, 10, 11, 11, 10, 10],
       [11, 10, 10, 10, 11, 11, 10, 10, 11, 10],
       [11, 11, 11, 11, 10, 10, 11, 10, 11, 10],
       [10, 10, 10, 11, 11, 11, 11, 11, 10, 10]], dtype=int32)

In [60]:
np.random.randint(10,20,10)

array([19, 12, 15, 18, 18, 13, 18, 15, 14, 16], dtype=int32)

In [ ]:
np.random.randint(10,20,(10,10))

array([[12, 11, 12, 10, 18, 16, 15, 18, 16, 13],
       [17, 15, 16, 10, 15, 12, 16, 16, 15, 13],
       [10, 18, 15, 12, 16, 11, 15, 19, 14, 18],
       [11, 17, 13, 16, 13, 18, 12, 11, 17, 12],
       [13, 17, 13, 11, 14, 11, 16, 15, 14, 16],
       [19, 18, 16, 18, 14, 18, 16, 14, 11, 10],
       [17, 16, 19, 17, 17, 15, 17, 11, 14, 10],
       [17, 17, 12, 12, 17, 10, 13, 14, 10, 19],
       [15, 18, 19, 13, 17, 12, 15, 19, 10, 12],
       [18, 16, 11, 12, 16, 19, 10, 19, 14, 15]], dtype=int32)

4. array attributes

In [ ]:
# difference between attributes and methods
'''
attributes are kind of variables defined inside a class and method are kind of functions defined inside a class 
'''


'\nattributes are kind of variables defined inside a class and method are kind of functions defined inside a class \n'

In [ ]:
arr = np.array([[1,2,3], [4,0,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arr.shape

In [65]:
arr.shape

(3, 3)

In [73]:
arr.size

9

In [74]:
arr.dtype

dtype('int64')

In [75]:
arr.itemsize

8

5. arrays methods

In [ ]:
arr = np.array([[1,44,5], [0,-5, 8], [23, 9, 5]])
arr

array([[ 1, 44,  5],
       [ 0, -5,  8],
       [23,  9,  6]])

In [78]:
arr.min()

np.int64(-5)

In [79]:
arr.max()

np.int64(44)

In [80]:
arr.mean()

np.float64(10.11111111111111)

In [91]:
arr.astype(float)

array([[ 1., 44.,  5.],
       [ 0., -5.,  8.],
       [23.,  9.,  6.]])

In [83]:
arr_copy = arr.copy()

In [84]:
arr.copy()

array([[ 1, 44,  5],
       [ 0, -5,  8],
       [23,  9,  6]])

In [92]:
print(arr)
arr = arr.astype(float)
print(arr)
print(arr_copy)

[[ 1 44  5]
 [ 0 -5  8]
 [23  9  6]]
[[ 1. 44.  5.]
 [ 0. -5.  8.]
 [23.  9.  6.]]
[[ 1 44  5]
 [ 0 -5  8]
 [23  9  6]]


In [93]:
arr2 = arr

In [97]:
print(arr)
arr = arr.astype(int)
print(arr)
print(arr2)

[[ 1. 44.  5.]
 [ 0. -5.  8.]
 [23.  9.  6.]]
[[ 1 44  5]
 [ 0 -5  8]
 [23  9  6]]
[[ 1. 44.  5.]
 [ 0. -5.  8.]
 [23.  9.  6.]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr.sum()


np.int64(45)

In [105]:
arr[0].sum()

np.int64(6)

In [106]:
arr[0][0].sum()

np.int64(1)

In [108]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [110]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [ ]:
arr[0]

array([1, 2, 3])

In [112]:
arr[0].mean()

np.float64(2.0)

In [113]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax() # index of maximum element

np.int64(8)

In [116]:
arr.argmin() # index of maximum element

np.int64(0)

6. reshaping and resizing

In [118]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5) # 6 * 5 = 30

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.resize(arr, 10)

TypeError: resize() takes 2 positional arguments but 3 were given

In [ ]:
a = arr.resize(3, 3, refcheck=False) # data loss
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])