Numpy indexing and slicing of vectors

In [ ]:
''' 
1. Numpy indexing and slicing of vectors
2. Numpy indexing and slicing of matrix
3. Boolean indexing
'''

In [3]:
import numpy as np

In [4]:
arr = np.arange(11, 21)
arr 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[0]

np.int64(11)

In [7]:
arr[9]

np.int64(20)

In [9]:
arr = np.array([np.arange(1,5), np.arange(5,9)])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr[0]

array([1, 2, 3, 4])

In [12]:
arr[1]

array([5, 6, 7, 8])

In [6]:
# slicing
arr[2:5]

array([13, 14, 15])

In [7]:
arr[:6]

array([11, 12, 13, 14, 15, 16])

In [8]:
arr[1:111]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[-1]

np.int64(20)

In [11]:
arr[:-1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
arr[3::2]

array([14, 16, 18, 20])

In [22]:
arr = np.arange(1,31).reshape(5, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [28]:
print(arr[0][0])
print(arr[0,0])


1
1


In [29]:
arr[0,5]

np.int64(6)

In [30]:
arr[4,5]

np.int64(30)

In [35]:
arr[0:2, 2:4]

array([[ 3,  4],
       [ 9, 10]])

In [44]:
arr[2:3, 0:3]

array([[13, 14, 15]])

In [42]:
arr[2:, 4:]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [46]:
arr[:, 2:]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24],
       [27, 28, 29, 30]])

In [48]:
arr[0:, 2:]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24],
       [27, 28, 29, 30]])

In [49]:
arr[:, 3]

array([ 4, 10, 16, 22, 28])

3. Boolean indexing

In [51]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
# extract all even numbers
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [54]:
bool_index.astype(int)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [55]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [57]:
arr = arr[bool_index]
arr

IndexError: boolean index did not match indexed array along axis 0; size of axis is 5 but size of corresponding boolean axis is 10

In [58]:
arr

array([12, 14, 16, 18, 20])

In [74]:
arr = np.arange(21)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [76]:
bool_index = arr % 3 != 0
bool_index

array([False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True])

In [ ]:
# bool_index = bool_index.astype(int)
# bool_index

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False])

In [77]:
arr = arr[bool_index]
arr

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20])