Array operations

'''
1. Arithmetic operations
2. Broadcasting
3. Deep and shallow copy
4. Matrix operations
5. Advance array manipulation
6. Stacking array
7. Splitting array

'''

Arithmetic operations

In [3]:
import numpy as np

In [10]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [6]:
a2

array([ 6,  7,  8,  9, 10])

In [12]:
arr2 = a1 + a2 # array size should be same

In [13]:
arr2

array([ 7,  9, 11, 13, 15])

In [14]:
a1-a2

array([-5, -5, -5, -5, -5])

In [15]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [16]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [17]:
a1 // a2

array([0, 0, 0, 0, 0])

In [18]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [19]:
lst = [10,20,30,40]
arr = np.array(lst)

In [20]:
lst+10

TypeError: can only concatenate list (not "int") to list

In [21]:
lst+lst

[10, 20, 30, 40, 10, 20, 30, 40]

In [23]:
for val in lst:
    print(val+10)

20
30
40
50


In [ ]:
arr + 10 #basic case scenario of broadcasting

array([20, 30, 40, 50])

In [30]:
arr

array([10, 20, 30, 40])

In [26]:
a = [10]

In [27]:
arr + a

array([20, 30, 40, 50])

In [29]:
a = np.array([11])
a

array([11])

In [31]:
arr + a

array([21, 31, 41, 51])

In [32]:
a = np.array([1, 2, 3])
b = 10

print(a + b)

[11 12 13]


In [33]:
a = np.array([1, 2, 3])
b = np.array([10])

print(a + b)

[11 12 13]


In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2])

print(a + b)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [36]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [41]:
a = np.array([[1,1,1],
              [2,2,2],
              [3,3,3]])

b = np.array([[10, 20, 30],
             [10, 20, 30],
             [10, 20, 30]])

print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


3. Deep and shallow copy


In [44]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [47]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [48]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
a[4:6] * 20

array([100, 120])

In [51]:
a
b = a

In [52]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
b[0] = 99

In [55]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
print(a)
print(b)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [58]:
b = a.copy()

In [62]:
print(a)
print(b)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
b[0] = 111
b

array([111,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [64]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
a[0] = 3333
a

array([3333,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [67]:
b

array([111,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

Matrix operations

In [85]:
mat1 = np.arange(1,31).reshape(6,5)
mat2 = np.arange(31,61).reshape(5,6)

In [86]:
print(mat1)
print()
print(mat2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [87]:
mat1 * mat2 # this is not actual matrix multiplication this is just element multiplication of both arrays

ValueError: operands could not be broadcast together with shapes (6,5) (5,6) 

In [88]:
# matrix multiplication
mat1 @ mat2

array([[ 705,  720,  735,  750,  765,  780],
       [1780, 1820, 1860, 1900, 1940, 1980],
       [2855, 2920, 2985, 3050, 3115, 3180],
       [3930, 4020, 4110, 4200, 4290, 4380],
       [5005, 5120, 5235, 5350, 5465, 5580],
       [6080, 6220, 6360, 6500, 6640, 6780]])

In [80]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [81]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [96]:
print(A @ B)
# or 
print(np.dot(A,B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [84]:
print(mat1.shape)
print(mat2.shape)

(6, 5)
(6, 5)


In [89]:
mat1 = np.arange(1,31).reshape(6,5)
mat2 = np.arange(31,61).reshape(6,5)

In [94]:
print(mat1)
print()
print(mat2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [93]:
mat1.T @ mat2

array([[3961, 4042, 4123, 4204, 4285],
       [4222, 4309, 4396, 4483, 4570],
       [4483, 4576, 4669, 4762, 4855],
       [4744, 4843, 4942, 5041, 5140],
       [5005, 5110, 5215, 5320, 5425]])

In [95]:
mat1 @ mat2.T

array([[ 505,  580,  655,  730,  805,  880],
       [1330, 1530, 1730, 1930, 2130, 2330],
       [2155, 2480, 2805, 3130, 3455, 3780],
       [2980, 3430, 3880, 4330, 4780, 5230],
       [3805, 4380, 4955, 5530, 6105, 6680],
       [4630, 5330, 6030, 6730, 7430, 8130]])

In [99]:
# transpose
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


5. Advance array manipulation
6. Stacking array
7. Splitting array

In [100]:
A

array([[1, 2],
       [3, 4]])

In [101]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# stacking - stack or merge two arrays
# we can perform stacking operation only in vectors or in one dimentional not in matrix
# we cannot stack 2 matrix because it is already stacked

In [103]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [105]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [111]:
# splitting array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [113]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [115]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [116]:
np.hsplit(c,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [117]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [118]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [119]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [123]:
a = np.array_split(c,2)

In [124]:
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [125]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arr = np.array([1,2,3,4])
np.split(arr,2)

ValueError: vsplit only works on arrays of 2 or more dimensions