1. valid sudoku

In [2]:
import numpy as np

In [48]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],  # sum of a row must be 45 (1 + ... + 9 = 45) also for  column sum will be 45
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9] 
])



In [5]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [6]:
np.sum(s, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [12]:
b = np.sum(s, axis=1)
b[b == 45]
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [13]:
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [15]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("sudoku is valid for rows")

sudoku is valid for rows


In [17]:
c = np.sum(s, axis=0)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for columns")

Sudoku is valid for columns


In [18]:
mat1 = s[0:3, 0:3]
mat1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [27]:
np.sum(mat1)

np.int64(45)

In [29]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        print(s[i:i+3, j:j+3])
        print(np.sum(s[i:i+3, j:j+3]))

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


In [49]:
valid = True

for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        if np.sum(s[i:i+3, j:j+3]) != 45:
            print("Sudoku is invalid")
            valid = False
            break
    if not valid:
        break

if valid:
    print("Sudoku is valid")

def check_sudoku(s):
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            if np.sum(s[i:i+3, j:j+3]) != 45:
                return "Sudoku is invalid"
    return "Sudoku is valid"

print(check_sudoku(s))


Sudoku is valid
Sudoku is valid


In [154]:
# Get the shape of the matrix

# columns: [Age, math marks, science marks]

data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

data.shape

(5, 3)

In [58]:
# find the average age of students
age = data[:, 0]
print(np.average(age))
print(age.sum() / age.size)
print(np.mean(data[:, 0]))

18.4
18.4
18.4


In [60]:
# Extract math marks of all students
data[:, 1]

array([85, 92, 76, 65, 90])

In [ ]:
# Find the highest science mark.
science_marks = data[:, 2]
np.max(science_marks)
# or
science_marks.max()

np.int64(95)

In [105]:
# Get details of the student who scored more than 90 in Math.

# marks = data[:, 1]
# marks[marks >= 90]
# print(marks)
# index = marks > 100
# index = index.astype(int)
# index
# print(data[index])



# 
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [106]:
# Increase math marks of all students by 5.

math_marks = data[:, 1]
math_marks += 5
math_marks

array([90, 97, 81, 70, 95])

In [121]:
# find how many students are younger than 19

# data
# age = data[:, 0]
# age[age < 19]

len(data[data[:, 0] < 19])

3

In [126]:
# calculate the average marks in each subject (column-wise mean).
np.mean(data[:, 1:], axis=0)

array([86.6, 83.2])

In [ ]:
# Get data of students who scored at least 80 in both subject
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)] 
# here for and operation we will use & sign

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
# Replace all science marks < 75 with 0. 
print(data)

# data[:, 2][data[:, 2] < 75] = 0
data[:, 2][data[:, 2] > 90] = 0
data

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76,  0],
       [18, 65,  0],
       [20, 90, 85]])

In [ ]:
# Numpy